<?php
//For ajax request login
if ('js' == $block['type']) { 
?>
<ul class="nav navbar-nav navbar-left" id="user-bar-anonymous" style="display: none;">
    <li>
        <a href="<?php echo $block['user']['login']; ?>">
            <?php echo _b('Login'); ?>
        </a>
    </li>    
    <li>
         <a href="<?php echo $block['user']['register']; ?>">
            <?php echo _b('Register'); ?>
         </a>
    </li>     
</ul>
<ul class="nav navbar-nav navbar-right" id="user-bar-member" style="display: none;">
    <li>
        <a id="member-profile" href="#" title="<?php echo _b('Profile'); ?>">

        </a>
    </li>
    <li>
        <a id="member-logout" href="<?php echo $block['user']['logout']; ?>">
            <?php echo _b('Logout'); ?>
        </a>
    </li>
</ul>
<script>
    $.getJSON("<?php echo $block['callback']; ?>?" + new Date().getTime(), function (user) {
        var ela = $('#user-bar-anonymous');
        var elm = $('#user-bar-member');

        if (user.uid > 0) {
            ela.hide();
            elm.show();
            $('#member-avatar').html(user.avatar);
            $('#member-message').attr('href', user.message);
            $('#member-profile').attr('href', user.profile).html(user.name);
        } else {
            ela.show();
            elm.hide();
        }
    });
</script>
<?php
return;
}
?>
<ul class="nav navbar-nav navbar-left">
<?php if ('dropdown' == $block['type']) { ?>
    <!-- Dropdown display mode: logged in - user avatar, dropdown menu with user name with link to user profile, link to logout; guest - link to login, link to register  -->
    <?php
    if (!$block['user']['uid']) { ?>
    <li>
        <a href="<?php echo $block['user']['login']; ?>">
            <?php echo _b('Login'); ?>
        </a>
    <li>
        <a href="<?php echo $block['user']['register']; ?>">
            <?php echo _b('Register'); ?>
        </a>
    <?php
    } else {
        ?>
    <li class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
            <i class="icon-user"></i>
            <?php echo _escape($block['user']['name']); ?>
            <span class="caret"></span>
        </a>
        <ul class="dropdown-menu">
            <li><a href="<?php echo $block['user']['profile']; ?>" title="<?php echo _b('Profile'); ?>"><?php echo _b('Profile'); ?></a>
            <li><a href="<?php echo $block['user']['logout']; ?>" title="<?php echo _b('Logout'); ?>"><?php echo _b('Logout'); ?></a>
        </ul>
    <?php
    }
    ?>
<?php } else { ?>
    <?php
        if (!$block['user']['uid']) { ?>
        <li><a title="ورود" href="<?php echo $block['user']['login']; ?>"><i class="fa fa-sign-in"></i> ورود</a></li>   
        <li><a title="ثبت نام" href="<?php echo $block['user']['register']; ?>"><i class="fa fa-arrow-circle-down"></i> ثبت نام</a></li>
    <?php
        } else {
    ?>
        <li><span><?php echo $block['user']['name']; ?> خوش آمدید</span></li>
        <li><a title="خرید های من" href="<?php echo $this->url('home'); ?>discount/user"><i class="fa fa-user"></i> خرید های من</a></li>
        <li><a title="پروفایل" href="<?php echo $block['user']['profile']; ?>"><i class="fa fa-cog"></i> پروفایل</a></li>
        <li><a title="خروج" href="<?php echo $block['user']['logout']; ?>"><i class="fa fa-sign-out"></i> خروج</a></li>   
    <?php
        }
    ?>
<?php } ?>
</ul>